# Incoming message format (recipient's point of view)
# Placeholders:
#  <sender> - the username of the message sender
#  <recipient> - the username of the message recipient
#  <message> - the message text
incoming: '<click:suggest_command:/msg <sender> ><dark_gray>[<#60a5fa><sender></#60a5fa> <white>-></white> <#bfdbfe>me</#bfdbfe>]</dark_gray></click> <reset><#dbeafe><message></#dbeafe>'

# Outgoing message format (sender's point of view)
# Same placeholders as incoming
outgoing: '<click:suggest_command:/msg <recipient> ><dark_gray>[<#93c5fd>me</#93c5fd> <white>-></white> <#60a5fa><recipient></#60a5fa>]</dark_gray></click> <reset><#dbeafe><message></#dbeafe>'

# Player has successfully been ignored
# Placeholders:
#  <player> - the player's username
ignored: "<green>(!) You will no longer see messages from <gray><player></gray>.</green>"

# Player has successfully been unignored
# Same placeholders as ignored
unignored: "<yellow>(!) You are no longer ignoring <gray><player></gray>.</yellow>"

channel:
    # Message channel created
    # Placeholders:
    #  <sender> - the username of the message sender
    #  <recipient> - the username of the message recipient
    #  <command> - the command used, e.g. `msg`, `dm`, etc.
    created: <green>(!) Your chat messages will now be sent as private messages to <gray><recipient></gray>. To re-enable public messages, run <click:suggest_command:/<command> <recipient>><gray>/<command> <recipient></gray></click></green>

    # Message channel closed
    # Same placeholders as created
    closed: <yellow>(!) Your chat messages will now be <gray>public</gray>.</yellow>

    # Message channel player is offline and channel closed
    # Placeholders:
    #  <sender> - the username of the message sender
    #  <recipient> - the username of the message recipient
    offline: <red>(!) Player <gray><recipient></gray> is offline. Your chat messages have been switched back to <gray>public</gray>.</red>

# Name for console/server that should appear as <sender> or <recipient> in messages
console-name: "Server"

# Command usage format
# Placeholders:
#  <command> - the command name
#  <usage> - the command usage parameters
usage: "<yellow>(!) Usage:</yellow> <white>/<command> <usage></white>"

# Plugin reloaded
reloaded: "<green>(!) Plugin successfully reloaded.</green>"

# Error messages
errors:
    # No permission
    no-permission: "<red>(!) You don't have permission to use this command.</red>"

    # Player has no username (somehow)
    invalid-player: "<red>(!) Invalid player.</red>"

    # Player not found
    # Placeholders:
    #  <player> - the player's username
    player-not-found: "<red>(!) Player <gray><player></gray> not found.</red>"

    message-yourself: "<red>(!) You can't send a message to yourself.</red>"

    nobody-reply: "<red>(!) You have no one to reply to.</red>"

    # The player that messaged you is no longer online
    # Placeholders:
    #  <player> - the player's username
    reply-offline: "<red>(!) Player <gray><player></gray> is no longer online.</red>"

    # Only players can use this command
    not-player: "<red>(!) You must be a player to use this command.</red>"

    # That player is not ignored
    # Placeholders:
    #  <player> - the player's username
    not-ignored: "<red>(!) You are not ignoring that player.</red>"

    # Player cannot be ignored
    # Placeholders:
    #  <player> - the player's username
    cannot-ignore: "<red>(!) You cannot ignore <gray><player></gray>.</red>"

    # Target player has never joined the server
    # Placeholders:
    #  <player> - the player's username
    never-joined: "<red>(!) <gray><player></gray> has never joined this server.</red>"
